import { StyleSheet,Dimensions } from 'react-native'
import React from 'react'

const {width, height} = Dimensions.get('window');  
 
import Colors from '../utility/color';
import FontSize ,{FontWeight} from '../utility/fonts';

 const styles = new StyleSheet.create({
    DarkHeder:{
        width:'100%', 
        backgroundColor:'#E5E5E5',
        flexDirection:'row',
        justifyContent:'flex-start',
        alignContent:'center',
        alignItems:'center',
        paddingHorizontal:10
    },
    textInputContiner:{
        height:55,width:'100%',flexDirection:'row',
        justifyContent:'center',alignItems: 'center',alignContent:'center',
        borderRadius:13,borderWidth:2 
    },
    textInput:{
        color:Colors.black,
        width:'70%',height:'100%',
        borderTopLeftRadius:12,
        borderBottomLeftRadius:12,
        paddingHorizontal:10,
        fontSize:FontSize.h6
    }, 
    Container:{
        width:'100%',  
        position:'relative',
        marginTop:10,
        marginBottom:12,  
        borderRadius:12
    },
    InnerBoxShadow:{
        width:'100%',
        minHeight:80, 
        backgroundColor:Colors.PrimaryColor,  
        borderTopLeftRadius:12,
        borderTopRightRadius:12,
        borderBottomLeftRadius:12,
        borderBottomRightRadius:12,
        position:'absolute',
        top:-2, 
    }, 
    InnerBox:{
        width:'100%',
        minHeight:80, 
        backgroundColor:'#fff',
        borderRadius:12, 
        elevation:3,  
        paddingBottom:22
    }, 
    PaymentDetails:{
        width:'100%',height:50,
        borderWidth:2,
        borderColor:Colors.lighteshGray,
        borderRadius:9,
        flexDirection:'row',justifyContent:'space-between',
        alignContent:'center',alignItems:'center',
        padding:10,
        color:Colors.black, 
        marginBottom:12 
    }, 
    couponConformContainer:{
        width: '100%',  
        padding:8
    },
    couponCodeInner:{
        flexDirection:'row',
        justifyContent:"space-between",
        alignContent:'center',
        alignItems:'center',
        width:'100%',
        minHeight:50, 
        padding:12,
        borderRadius:6,
        borderWidth:2,
        borderColor:Colors.PrimaryColor,  
        backgroundColor:'#E5F6EC'
    },
    couponCodeInnerText:{
        fontSize:FontSize.xxp,
        fontWeight:FontWeight.medium,
        color:Colors.PrimaryColor
    },
    BoxContainer:{
        minHeight:50,
        width:width,
        backgroundColor:'#F5F9FC',
        padding:12,
        flexDirection:'column',
        paddingTop:22,
        paddingBottom:33,
    
    },
    BoxTitle:{
        fontSize:FontSize.h6,
        fontWeight:FontWeight.bold,
        fontFamily: 'Inter-SemiBold',
        color:Colors.black,
        marginBottom:12
    },
    InnerBoxContainer:{
        width:'100%',
        minHeight:20, 
    },
    InnerBoxContainerItem:{
        width:'100%',
        minHeight:20,
        backgroundColor:'#ffffff',
        borderColor:'#E9E9E9',
        borderWidth:2,
        borderRadius:9,
        overflow:'hidden', 
        paddingHorizontal:12,
        paddingTop:4, 
        paddingBottom:12
    },
    ItemUpperTextBox:{
        flexDirection:'row',
        justifyContent:'space-between', 
        marginBottom:0
    },
    itemsmallTextPrice:{
        fontSize:FontSize.xxp,
        fontWeight:FontWeight.medium,
        color:'#949494'
    },
    itemMainTextPrice:{
        fontSize:FontSize.p+1, 
        color:'#000000',
        fontWeight:FontWeight.medium
    },
    BoxContainerStrip:{
        width:'100%',
        minHeight:50,
        backgroundColor:'#E5E5E5',
        justifyContent:'center',
        alignContent:'center',
        alignItems:'center'
    },
    BoxContainerStripText:{
        fontSize:FontSize.xp,
        color:Colors.SecondaryColor,
        fontWeight:FontWeight.medium
    },
    OfferInnerItems:{
        width:'100%',
        minHeight:20,
        backgroundColor:'#ffffff',
        elevation:0.1,
        borderRadius:9, 
        flexDirection:'column',
        overflow:'hidden' 
    },  
    UpperSection:{
        width:'100%',
        minHeight:40, 
        padding:12
    },
    LowwerSection:{
        width:'100%',
        height:45,
        backgroundColor:'#E4EAEC',
        padding:12,
        flexDirection:'row'
    },
    BillingDetails:{
        width:'100%',
        minHeight:20,
        backgroundColor:'#ffffff',
        borderWidth:2,
        borderColor:'#E9E9E9',
        borderRadius:9,
        overflow:'hidden', 
        paddingHorizontal:12,
        paddingVertical:10, 
    },
    PricingText:{
        fontSize:FontSize.p,
        fontWeight:'400',
        color:'#000000'
    },
    PricingTextPrice:{
        fontSize:FontSize.xp,
        fontWeight:'500',
        color:'#000000'
    }, 
    InnerHelpBox:{ 
        width:'100%',
        height:50,
        backgroundColor:'#ffffff',
        borderRadius:9,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems: 'center',
        alignContent:'center',
        paddingHorizontal:12 
    },
    couponCodeBox:{
        width:'100%',
        minHeight:50, 
        borderRadius:9,
        borderWidth:2,
        borderColor:'#D0D0D0',
        padding:8,
        marginBottom:16
    }

});

export default styles;